"""Puppetmaster CLI package — public facade preserving puppetmaster.cli imports."""

from __future__ import annotations

# Stdlib / typing names exposed on the historical module surface.
import argparse
import dataclasses
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Optional, TextIO

from puppetmaster.cli._dispatch import _main, _resolve_store_for_job, main
from puppetmaster.cli._parser import build_parser
from puppetmaster.cli.commands_codegraph import (
    _hoist_global_codegraph_flags,
    _run_codegraph_passthrough,
    _run_repair_codegraph,
)
from puppetmaster.codegraph_repair import repair_codegraph_sqlite
from puppetmaster.cli.commands_gate import (
    _gate_specs_from_args,
    _parse_inline_rules,
    _run_affected_command,
    _run_audit_command,
    _run_cost_command,
    _run_gate_command,
    _run_invocation_gate_command,
    _run_preflight_command,
    _run_proxy_command,
    _run_rollup_command,
    _run_route_command,
    _run_savings_command,
    _run_should_delegate_command,
)
from puppetmaster.cli.commands_install import (
    _confirm_uninstall,
    _detected_platforms,
    _install_hermes_rule_status,
    _purge_uninstall_state,
    _run_install_claude,
    _run_install_codex,
    _run_install_cursor,
    _run_install_hermes,
    _run_install_hooks,
    _run_install_rules,
    _run_self_update,
    _run_setup,
    _run_uninstall,
    _seed_hermes_registry,
    _seed_agentic_registry,
    _agentic_providers_visible,
    _setup_hermes_advanced,
    _setup_next_steps,
    _setup_platform_step,
)
from puppetmaster.cli.commands_jobs import (
    _gc_target_stores,
    _reap_quietly,
    _resolved_store_root,
    _run_await_command,
    _run_finalize_command,
    _run_gc_command,
    _run_reap_command,
    _run_wait_command,
    await_job_state,
)
from puppetmaster.cli.commands_mcp import (
    _run_mcp_cleanup,
    _run_mcp_doctor,
    _run_mcp_list,
    _run_mcp_subcommand,
)
from puppetmaster.cli.commands_models import (
    ModelRegistryWizard,
    _DiscoverSourceError,
    _DISCOVER_SOURCE_BY_ADAPTER,
    _all_discover_sources,
    _default_discover_sources,
    _discover_one_source,
    _json_assignment_value,
    _parse_bool_value,
    _payload_defaults_summary,
    _replace_model_spec,
    _run_models_discover,
    _run_models_set,
    _run_models_setup,
    _run_models_subcommand,
    _updated_spec_for_assignment,
    model_payload_defaults_for_effort,
)
from puppetmaster.cli.commands_platform import (
    _run_platform_subcommand,
    _run_skills_subcommand,
)
from puppetmaster.cli.guidance import (
    CLAUDE_NEXT_STEPS_GUIDANCE,
    CODEX_SANDBOX_GUIDANCE,
    CURSOR_NEXT_STEPS_GUIDANCE,
    HERMES_NEXT_STEPS_GUIDANCE,
    _CLAUDE_CODE_EFFORT_LEVELS,
    _CODEX_EFFORT_LEVELS,
    _EFFORT_TOKEN_MULTIPLIERS,
    _HERMES_EFFORT_LEVELS,
    _NOISY_LOG_EVENTS,
    _OPENAI_EFFORT_LEVELS,
)
from puppetmaster.cli.helpers import (
    _print_codegraph_freshness,
    _print_install_result,
    _print_rules_result,
    _print_token_usage,
    _print_uninstall_hooks_result,
    _print_uninstall_mcp_result,
    _print_uninstall_rules_result,
    _registry_path_from_args,
    _warn_job_liveness,
    _warn_run_quality,
    apply_patch_diff,
    approve_target,
    artifact_feed,
    artifact_feed_since,
    artifact_headline,
    artifact_job_id,
    cursor_prompt,
    early_job_printer,
    emit_feed_item,
    finalize_cli_run,
    patch_artifacts_for_target,
    print_feed_item,
    print_mode_banner,
    print_run_result,
    print_watch_snapshot,
    reject_target,
    require_latest_job_id,
    routing_payload_from_args,
    run_deltas_follow,
    run_feed_follow,
)
from puppetmaster.config import load_config
from puppetmaster.diagnostics import adapter_status, run_doctor, starter_config
from puppetmaster.hook_installers import (
    VALID_HOOK_TARGETS,
    install_hermes_hooks,
    install_hooks,
    uninstall_hermes_hooks,
    uninstall_hooks,
)
from puppetmaster.installers import (
    InstallResult,
    UninstallResult,
    ensure_cursor_sdk,
    install_claude_mcp,
    install_codex_mcp,
    install_cursor_mcp,
    install_hermes_mcp,
    install_hermes_plugin,
    install_hermes_skill,
    list_skill_candidates,
    promote_skill_candidate,
    resolve_claude_command,
    set_hermes_mcp_env,
    uninstall_claude_mcp,
    uninstall_codex_mcp,
    uninstall_cursor_mcp,
    uninstall_hermes_mcp,
)
from puppetmaster.mcp_registry import (
    kill_stale as registry_kill_stale,
    list_entries as registry_list_entries,
    prune_dead as registry_prune_dead,
    summarize as registry_summarize,
)
from puppetmaster.orchestrator import Orchestrator
from puppetmaster.redaction import redact_secrets
from puppetmaster.rules import (
    VALID_TARGETS,
    RulesInstallResult,
    install_rules,
    uninstall_rules,
)
from puppetmaster.state import (
    find_state_dir_for_job,
    list_project_state_dirs,
    resolve_state_dir,
)
from puppetmaster.store_factory import create_store
from puppetmaster.stitcher import Stitcher
from puppetmaster.worker_runtime import WorkerDaemon
from puppetmaster.workers import WorkerSpec

__all__ = [
    "Any",
    "CLAUDE_NEXT_STEPS_GUIDANCE",
    "CODEX_SANDBOX_GUIDANCE",
    "CURSOR_NEXT_STEPS_GUIDANCE",
    "HERMES_NEXT_STEPS_GUIDANCE",
    "InstallResult",
    "ModelRegistryWizard",
    "Optional",
    "Orchestrator",
    "Path",
    "RulesInstallResult",
    "Stitcher",
    "TextIO",
    "UninstallResult",
    "VALID_HOOK_TARGETS",
    "VALID_TARGETS",
    "WorkerDaemon",
    "WorkerSpec",
    "_CLAUDE_CODE_EFFORT_LEVELS",
    "_CODEX_EFFORT_LEVELS",
    "_DISCOVER_SOURCE_BY_ADAPTER",
    "_DiscoverSourceError",
    "_EFFORT_TOKEN_MULTIPLIERS",
    "_HERMES_EFFORT_LEVELS",
    "_NOISY_LOG_EVENTS",
    "_OPENAI_EFFORT_LEVELS",
    "_all_discover_sources",
    "_confirm_uninstall",
    "_default_discover_sources",
    "_detected_platforms",
    "_discover_one_source",
    "_gate_specs_from_args",
    "_gc_target_stores",
    "_hoist_global_codegraph_flags",
    "_install_hermes_rule_status",
    "_json_assignment_value",
    "_main",
    "_parse_bool_value",
    "_parse_inline_rules",
    "_payload_defaults_summary",
    "_print_codegraph_freshness",
    "_print_install_result",
    "_print_rules_result",
    "_print_token_usage",
    "_print_uninstall_hooks_result",
    "_print_uninstall_mcp_result",
    "_print_uninstall_rules_result",
    "_purge_uninstall_state",
    "_reap_quietly",
    "_registry_path_from_args",
    "_replace_model_spec",
    "_resolve_store_for_job",
    "_run_affected_command",
    "_run_audit_command",
    "_run_await_command",
    "_run_codegraph_passthrough",
    "_run_cost_command",
    "_run_finalize_command",
    "_run_gate_command",
    "_run_gc_command",
    "_run_install_claude",
    "_run_install_codex",
    "_run_install_cursor",
    "_run_install_hermes",
    "_run_install_hooks",
    "_run_install_rules",
    "_run_invocation_gate_command",
    "_run_mcp_cleanup",
    "_run_mcp_doctor",
    "_run_mcp_list",
    "_run_mcp_subcommand",
    "_run_models_discover",
    "_run_models_set",
    "_run_models_setup",
    "_run_models_subcommand",
    "_run_platform_subcommand",
    "_run_preflight_command",
    "_run_proxy_command",
    "_run_reap_command",
    "_run_repair_codegraph",
    "_run_rollup_command",
    "_run_route_command",
    "_run_savings_command",
    "_run_self_update",
    "_run_setup",
    "_run_should_delegate_command",
    "_run_skills_subcommand",
    "_run_uninstall",
    "_run_wait_command",
    "_seed_hermes_registry",
    "_seed_agentic_registry",
    "_agentic_providers_visible",
    "_setup_hermes_advanced",
    "_setup_next_steps",
    "_setup_platform_step",
    "_updated_spec_for_assignment",
    "_warn_job_liveness",
    "_warn_run_quality",
    "adapter_status",
    "annotations",
    "apply_patch_diff",
    "approve_target",
    "argparse",
    "artifact_feed",
    "artifact_feed_since",
    "artifact_headline",
    "artifact_job_id",
    "await_job_state",
    "build_parser",
    "create_store",
    "cursor_prompt",
    "dataclasses",
    "early_job_printer",
    "emit_feed_item",
    "ensure_cursor_sdk",
    "finalize_cli_run",
    "find_state_dir_for_job",
    "install_claude_mcp",
    "install_codex_mcp",
    "install_cursor_mcp",
    "install_hermes_hooks",
    "install_hermes_mcp",
    "install_hermes_plugin",
    "install_hermes_skill",
    "install_hooks",
    "install_rules",
    "json",
    "list_project_state_dirs",
    "list_skill_candidates",
    "load_config",
    "main",
    "model_payload_defaults_for_effort",
    "os",
    "patch_artifacts_for_target",
    "print_feed_item",
    "print_mode_banner",
    "print_run_result",
    "print_watch_snapshot",
    "promote_skill_candidate",
    "redact_secrets",
    "registry_kill_stale",
    "registry_list_entries",
    "registry_prune_dead",
    "registry_summarize",
    "reject_target",
    "repair_codegraph_sqlite",
    "require_latest_job_id",
    "resolve_claude_command",
    "resolve_state_dir",
    "routing_payload_from_args",
    "run_deltas_follow",
    "run_doctor",
    "run_feed_follow",
    "set_hermes_mcp_env",
    "starter_config",
    "subprocess",
    "sys",
    "time",
    "uninstall_claude_mcp",
    "uninstall_codex_mcp",
    "uninstall_cursor_mcp",
    "uninstall_hermes_hooks",
    "uninstall_hermes_mcp",
    "uninstall_hooks",
    "uninstall_rules",
]
